INSERT INTO PRODUCT 
(ID, AVAILABLE, BRAND, CATEGORY, "DESC", NAME, PRICE, QUANTITY, RELEASE_DATE)
VALUES
(1, TRUE, 'Apple', 'Electronics', 'Smartphone with iOS', 'iPhone 15', 999.99, 50, DATE '2024-09-20');

INSERT INTO PRODUCT 
(ID, AVAILABLE, BRAND, CATEGORY, "DESC", NAME, PRICE, QUANTITY, RELEASE_DATE)
VALUES
(2, TRUE, 'Samsung', 'Electronics', 'Android flagship phone', 'Galaxy S24', 899.99, 40, DATE '2024-10-10');

INSERT INTO PRODUCT 
(ID, AVAILABLE, BRAND, CATEGORY, "DESC", NAME, PRICE, QUANTITY, RELEASE_DATE)
VALUES
(3, FALSE, 'Sony', 'Electronics', 'Noise cancelling headphones', 'WH-1000XM5', 349.99, 0, DATE '2023-06-01');
